CREATE TABLE IF NOT EXISTS public.templates_meta (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  language text NOT NULL,
  category text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING',
  meta_id text NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT templates_meta_owner_name_language_unique UNIQUE (created_by, name, language)
);

CREATE TABLE IF NOT EXISTS public.campanha_templates (
  campanha_id bigint NOT NULL REFERENCES public.campanhas(id) ON DELETE CASCADE,
  template_id bigint NOT NULL REFERENCES public.templates_meta(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (campanha_id, template_id)
);

CREATE INDEX IF NOT EXISTS idx_templates_meta_created_by ON public.templates_meta(created_by);
CREATE INDEX IF NOT EXISTS idx_campanha_templates_template ON public.campanha_templates(template_id);

ALTER TABLE public.templates_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campanha_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own templates" ON public.templates_meta
  FOR ALL TO authenticated
  USING (created_by = (SELECT auth.uid()))
  WITH CHECK (created_by = (SELECT auth.uid()));

CREATE POLICY "Users read links from own campaigns" ON public.campanha_templates
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.campanhas c
    WHERE c.id = campanha_id AND c.created_by = (SELECT auth.uid())
  ));

CREATE POLICY "Users link own templates to own campaigns" ON public.campanha_templates
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.campanhas c WHERE c.id = campanha_id AND c.created_by = (SELECT auth.uid()))
    AND EXISTS (SELECT 1 FROM public.templates_meta t WHERE t.id = template_id AND t.created_by = (SELECT auth.uid()))
  );

CREATE POLICY "Users unlink templates from own campaigns" ON public.campanha_templates
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.campanhas c
    WHERE c.id = campanha_id AND c.created_by = (SELECT auth.uid())
  ));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.templates_meta TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.campanha_templates TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.templates_meta_id_seq TO authenticated;
GRANT ALL ON public.templates_meta, public.campanha_templates TO service_role;
GRANT ALL ON SEQUENCE public.templates_meta_id_seq TO service_role;

-- Preserve templates created before the reusable library existed.
WITH legacy AS (
  SELECT
    c.id AS campanha_id,
    c.created_by,
    item AS payload,
    item->>'name' AS name,
    COALESCE(NULLIF(item->>'language', ''), 'pt_BR') AS language,
    COALESCE(NULLIF(item->>'category', ''), 'MARKETING') AS category,
    COALESCE(NULLIF(item->>'status', ''), 'PENDING') AS status,
    item->>'meta_id' AS meta_id,
    COALESCE((item->>'submitted_at')::timestamptz, c.created_at) AS created_at
  FROM public.campanhas c
  CROSS JOIN LATERAL jsonb_array_elements(
    CASE
      WHEN c.templates_meta IS NULL THEN '[]'::jsonb
      WHEN jsonb_typeof(c.templates_meta) = 'array' THEN c.templates_meta
      ELSE jsonb_build_array(c.templates_meta)
    END
  ) item
  WHERE c.created_by IS NOT NULL AND NULLIF(item->>'name', '') IS NOT NULL
), inserted AS (
  INSERT INTO public.templates_meta (
    created_by, name, language, category, status, meta_id, payload, created_at, updated_at
  )
  SELECT created_by, name, language, category, status, meta_id, payload, created_at, created_at
  FROM legacy
  ON CONFLICT (created_by, name, language) DO UPDATE SET
    status = EXCLUDED.status,
    meta_id = COALESCE(EXCLUDED.meta_id, public.templates_meta.meta_id),
    payload = EXCLUDED.payload,
    updated_at = GREATEST(public.templates_meta.updated_at, EXCLUDED.updated_at)
  RETURNING id, created_by, name, language
)
INSERT INTO public.campanha_templates (campanha_id, template_id)
SELECT DISTINCT legacy.campanha_id, templates.id
FROM legacy
JOIN inserted templates
  ON templates.created_by = legacy.created_by
 AND templates.name = legacy.name
 AND templates.language = legacy.language
ON CONFLICT DO NOTHING;
