-- Campaign lifecycle. Keep these values stable because PostgreSQL enum values
-- may be added later, but removing/renaming them requires a data migration.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' AND t.typname = 'campanha_status'
  ) THEN
    CREATE TYPE public.campanha_status AS ENUM (
      'rascunho',
      'aguardando_aprovacao',
      'pronta',
      'em_andamento',
      'pausada',
      'concluida',
      'cancelada',
      'erro'
    );
  END IF;
END
$$;

ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'rascunho';
ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'aguardando_aprovacao';
ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'pronta';
ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'em_andamento';
ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'pausada';
ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'concluida';
ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'cancelada';
ALTER TYPE public.campanha_status ADD VALUE IF NOT EXISTS 'erro';

CREATE TABLE IF NOT EXISTS public.campanhas (
  id bigserial PRIMARY KEY,
  nome text NOT NULL,
  descricao text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  templates_meta jsonb NULL,
  status public.campanha_status NOT NULL DEFAULT 'rascunho'::public.campanha_status,
  meta_templates_status jsonb NOT NULL DEFAULT '{}'::jsonb,
  tipo smallint NOT NULL DEFAULT 0,
  CONSTRAINT campanhas_tipo_check CHECK (tipo IN (0, 1))
);

COMMENT ON COLUMN public.campanhas.tipo IS
  '0 = campanha de interacao; 1 = campanha com link';

CREATE INDEX IF NOT EXISTS idx_campanhas_status
  ON public.campanhas USING btree (status);

CREATE INDEX IF NOT EXISTS idx_campanhas_created_at
  ON public.campanhas USING btree (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_campanhas_created_by
  ON public.campanhas USING btree (created_by);

CREATE TABLE IF NOT EXISTS public.envio_em_massa (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telefone text NULL,
  nome text NULL,
  etapa bigint NULL DEFAULT 0,
  campanha_id bigint NULL REFERENCES public.campanhas(id) ON DELETE SET NULL,
  bsuid text NULL,
  etapa_manual_at timestamptz NULL,
  clicked_at timestamptz NULL,
  CONSTRAINT envio_em_massa_has_identifier CHECK (telefone IS NOT NULL OR bsuid IS NOT NULL),
  CONSTRAINT envio_em_massa_etapa_nonnegative CHECK (etapa IS NULL OR etapa >= 0)
);

-- CREATE TABLE IF NOT EXISTS does not add missing constraints to a table that
-- was previously created in the Dashboard, so reconcile them explicitly.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'campanhas_tipo_check' AND conrelid = 'public.campanhas'::regclass) THEN
    ALTER TABLE public.campanhas ADD CONSTRAINT campanhas_tipo_check CHECK (tipo IN (0, 1));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'envio_em_massa_has_identifier' AND conrelid = 'public.envio_em_massa'::regclass) THEN
    ALTER TABLE public.envio_em_massa ADD CONSTRAINT envio_em_massa_has_identifier CHECK (telefone IS NOT NULL OR bsuid IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'envio_em_massa_etapa_nonnegative' AND conrelid = 'public.envio_em_massa'::regclass) THEN
    ALTER TABLE public.envio_em_massa ADD CONSTRAINT envio_em_massa_etapa_nonnegative CHECK (etapa IS NULL OR etapa >= 0);
  END IF;
END
$$;

COMMENT ON COLUMN public.envio_em_massa.etapa IS
  'Etapa atual do contato; o significado depende do tipo e do fluxo da campanha';

CREATE INDEX IF NOT EXISTS idx_envio_em_massa_bsuid
  ON public.envio_em_massa USING btree (bsuid)
  WHERE bsuid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_envio_em_massa_clicked_at
  ON public.envio_em_massa USING btree (campanha_id)
  WHERE clicked_at IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_envio_em_massa_bsuid_unique
  ON public.envio_em_massa USING btree (bsuid)
  WHERE bsuid IS NOT NULL;

-- Main lookup used by the n8n workflow when dispatching one campaign stage.
CREATE INDEX IF NOT EXISTS idx_envio_em_massa_campanha_etapa
  ON public.envio_em_massa USING btree (campanha_id, etapa);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.campanhas TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.envio_em_massa TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campanhas_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.envio_em_massa_id_seq TO authenticated;
GRANT ALL ON public.campanhas TO service_role;
GRANT ALL ON public.envio_em_massa TO service_role;
GRANT ALL ON SEQUENCE public.campanhas_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.envio_em_massa_id_seq TO service_role;

ALTER TABLE public.campanhas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.envio_em_massa ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own campaigns" ON public.campanhas;
CREATE POLICY "Users read own campaigns"
  ON public.campanhas FOR SELECT TO authenticated
  USING (created_by = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users create own campaigns" ON public.campanhas;
CREATE POLICY "Users create own campaigns"
  ON public.campanhas FOR INSERT TO authenticated
  WITH CHECK (created_by = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users update own campaigns" ON public.campanhas;
CREATE POLICY "Users update own campaigns"
  ON public.campanhas FOR UPDATE TO authenticated
  USING (created_by = (SELECT auth.uid()))
  WITH CHECK (created_by = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users delete own campaigns" ON public.campanhas;
CREATE POLICY "Users delete own campaigns"
  ON public.campanhas FOR DELETE TO authenticated
  USING (created_by = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users read contacts from own campaigns" ON public.envio_em_massa;
CREATE POLICY "Users read contacts from own campaigns"
  ON public.envio_em_massa FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.campanhas c
      WHERE c.id = envio_em_massa.campanha_id
        AND c.created_by = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS "Users add contacts to own campaigns" ON public.envio_em_massa;
CREATE POLICY "Users add contacts to own campaigns"
  ON public.envio_em_massa FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.campanhas c
      WHERE c.id = envio_em_massa.campanha_id
        AND c.created_by = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS "Users update contacts from own campaigns" ON public.envio_em_massa;
CREATE POLICY "Users update contacts from own campaigns"
  ON public.envio_em_massa FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.campanhas c
      WHERE c.id = envio_em_massa.campanha_id
        AND c.created_by = (SELECT auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.campanhas c
      WHERE c.id = envio_em_massa.campanha_id
        AND c.created_by = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS "Users delete contacts from own campaigns" ON public.envio_em_massa;
CREATE POLICY "Users delete contacts from own campaigns"
  ON public.envio_em_massa FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.campanhas c
      WHERE c.id = envio_em_massa.campanha_id
        AND c.created_by = (SELECT auth.uid())
    )
  );
